mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as users_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plants/', include('plants.urls')),
    path('register/', users_views.register, name='register'),
]

mysite/plants/urls.py
from django.urls import path, include 
from plants import views 

app_name = 'plants'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('detail/<int:item_id>', views.detail, name='detail'),
    path('add/', views.create_item, name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

mysite/plants/models.py
from django.db import models

# Create your models here.

class Item(models.Model):
    prod_code = models.IntegerField(default=100)
    for_user = models.CharField(
        max_length=100,
        default='xyz'
    )
    item_name = models.CharField(max_length=50)
    item_desc = models.CharField(
        max_length=500,
        default='''Lorem, ipsum dolor sit amet consectetur adipisicing elit. A nam voluptate assumenda recusandae officia et consequatur, nobis voluptatem incidunt laborum harum doloribus aspernatur iure aperiam adipisci quas alias ea delectus!'''
    )
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500, 
        default="https://i.pinimg.com/736x/fa/d3/4a/fad34a707359c5c1bfe1a4461010b7a1.jpg"
    )

    def __str__(self):
        return self.item_name

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/plants/forms.py
from django import forms
from plants.models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['prod_code', 'for_user', 'item_name', 'item_desc', 'item_price', 'item_image']

mysite/plants/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from plants.models import Item
from plants.forms import ItemForm

# Create your views here.

def index(request):
    itemlist = Item.objects.all()

    context = {
        'itemlist':itemlist
    }

    return render(request, 'plants/index.html', context)

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)

    context = {
        'item':item
    }

    return render(request, 'plants/detail.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('plants:index')
    
    context = {
        'form':form
    }

    return render(request, 'plants/item-form.html', context)

def update_item(request, id):
    item = Item.objects.get(pk=id)
    form = ItemForm(request.POST or None, instance=item)

    context = {
        'form':form
    }

    if form.is_valid():
        form.save()
        return redirect('plants:index')
    
    return render(request, 'plants/item-form.html', context)

def delete_item(request, id):
    item = Item.objects.get(pk=id)

    context = {
        'item':item
    }

    if request.method == 'POST':
        item.delete()
        return redirect('plants:index')
    
    return render(request, 'plants/item-delete.html', context)

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    form = UserCreationForm()

    if form.is_valid():
        form.save()
        return redirect('plants:index')
    
    else:
        form = UserCreationForm()

        context = {
            'form':form
        }

    return render(request, 'users/register.html', context)

mysite/plants/templates/plants/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'plants/style.css' %}">
    <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <style>
        .search-bar{
            margin-right: 650px;
        }
    </style>
</head>
<body>
    

    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'plants:index' %}" class="navbar-brand">
            <img src="#" width="30" height="30" class="d-inline-block align-top" alt="">
            <font color="green" style="font-family: fantasy; font-size: 130%;">NATURAL GARDENER </font>
        </a>

        <div class="search-bar">
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div> 
        
        <div class="navbar">
            <a href="{% url 'plants:create_item' %}" class="nav-item nav-link btn btn-dark">
                Add Item
            </a>

            <a href="#" class="nav-item nav-link btn btn-dark">
                Profile
            </a>

            <a href="{% url 'register' %}" class="nav-item nav-link btn btn-dark">
                Sign Up
            </a>
        </div>


    </nav>

    


    <div class="md-5">
        
    </div>

    {% block body %}
    {% endblock %}


</body>
</html>

mysite/plants/templates/plants/detail.html
{% extends 'plants/base.html' %}

{% block body %}

<br><br>

<div class="row">
    <div class="col-md-2 offset-md-1">
        <img
            height="150px"
            width="250px"
            class="card"
            src="{{ item.item_image }}"
        >
    </div>

    <div class="col-md-4 offset-md-1">
        <h1
            style="
                font-style: italic;
            "
        >
            {{ item.item_name }}
        </h1>

        <h2
            style="
                font-style: italic;
                font-size: 1.3rem;
                text-align: justify;
            "
        >
            {{ item.item_desc }}
        </h2>

        <h3>
            ${{ item.item_price }}
        </h3>
    </div>

    <div class="col-md-3 offset-md-1">
        <a
            href="{% url 'plants:update_item' item.id %}"
            style="width:80px"
            class="btn btn-warning"
        >
            Edit
        </a>

        <a
            href="{% url 'plants:delete_item' item.id %}"
            style="width:80px"
            class="btn btn-danger"
        >
            Delete
        </a>

        <a
            href="{% url 'plants:index' %}"
            style="width:80px"
            class="btn btn-success"
        >
            Back
        </a>
    </div>
</div>

{% endblock %}

mysite/plants/templates/plants/index.html
{% extends 'plants/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}

    {% for item in itemlist %}
    <br><br><br>
        <div class="row mb-5">
            <div class="col-md-3 offset-md-2">
                <img 
                    src="{{ item.item_image }}"
                    class="card"
                    height="150px"
                    width="200px"
                >
            </div>

            <div class="col-md-4">
                <h3 style="font-size: 1.5rem;">
                    {{ item.item_name }}
                </h3>
                
                <h5 style="font-style: italic; font-size: 1rem;"> 
                    {{ item.item_desc | truncatewords:6 }}
                </h5>
                
                <h6>
                    ${{ item.item_price }}
                </h6>
                
                <h6 style="font-style: italic;">Added For: {{ item.for_user }}</h6>

                <h6 style="font-style: italic;">added by superuser: Admin </h6>
            </div>
            
            <div class="col-md-3">
                <a 
                    href="{% url 'plants:detail' item.id %}" 
                    style="width: 100px; "
                    class="btn btn-outline-success"
                >
                    Details
                </a>
        </div>
    </div>

    {% endfor %}

    {% endblock %}
</body>
</html>

mysite/plants/templates/plants/item-delete.html
{% extends 'plants/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}
    <h3>Are you sure you want to remove, {{ item.item_name }}</h3>
    <button type="submit">Confirm</button>
</form>

{% endblock %}

mysite/plants/templates/plants/item-form.html
{% extends 'plants/base.html' %}

{% block body %}

<br><br>

<form method="POST">
    {% csrf_token %}
    <label>Product Code: </label><br>
    {{ form.prod_code }}
    <br><label>For User: </label><br>
    {{ form.for_user }}
    <br><label>Item Name: </label><br>
    {{ form.item_name }}
    <br><label>Item Description: </label><br>
    {{ form.item_desc }}
    <br><label>Item Price: </label><br>
    {{ form.item_price }}
    <br><label>Item Image: </label><br>
    {{ form.item_image }}
    <br><button type="submit">Save</button>
</form>

{% endblock %}

mysite/users/templates/users/register.html
{% extends 'plants/base.html' %}

{% block body %}
<br><br>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign Up</button>
</form>

{% endblock %}